export interface items{
    channelID: string,
    channelImg: string,
    duration: string,
    thumbnails: string,
    title: string,
    uploadedAt: string,
    url: string,
    verified: string,
    views: string,
    description: string,
    channelTitle:string,
    subs:string,
    }


    
  // items? = [
  //   {
  //     channelID: "UCgqGpYjhnWvhE5-QrmXLkoQ",
  //     channelImg: "https://yt3.ggpht.com/ytc/AKedOLQ_DlBgMDMT4ARdLuB1dZXTFAoJ4aLNNgn1IBAf=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "The StudyTube Project",
  //     description: null,
  //     duration: "15:34",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/I-k-iTUMQAY/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBMWlD0HW9FwyDutkppZ3Ywz7jbmQ",
  //     title: "basics of CODING in 10 minutes",
  //     uploadedAt: "1 year ago",
  //     url: "https://www.youtube.com/watch?v=I-k-iTUMQAY",
  //     verified: false,
  //     views: 521716,
  //   } ,
  //   {
  //     channelID: "UCRLEADhMcb8WUdnQ5_Alk7g",
  //     channelImg: "https://yt3.ggpht.com/2Ic5G-MGcf0BGlxLo86TkUZILkxKCenzjCszCyVJSRcmn5xkEgtLgs4CBCkaK2YNoNdX4A66=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "Aaron Jack",
  //     description: null,
  //     duration: "5:59",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/CIRGjwYgdT4/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC8zR0ndjTZ3QCVuJMqp6Kb-G56UQ",
  //     title: "Programming vs Coding - What's the difference?",
  //     uploadedAt: "9 months ago",
  //     url: "https://www.youtube.com/watch?v=CIRGjwYgdT4",
  //     verified: true,
  //     views: 745652,
  //   } , 
  //   {
  //     channelID: "UCT5RMcRGa32Th0AZ0Dxxviw",
  //     channelImg: "https://yt3.ggpht.com/ytc/AKedOLRLLwKZPAC0lqMM8kQ-2a0Z6a5SC3Q3OB4sod2z=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "JimTV",
  //     description: null,
  //     duration: "1:00:03",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/l9nh1l8ZIJQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCjUXoFFhtydmIQO915lf-U4aebNA",
  //     title: "Programming / Coding / Hacking music vol.16 (CONN...",
  //     uploadedAt: "2 years ago",
  //     url: "https://www.youtube.com/watch?v=l9nh1l8ZIJQ",
  //     verified: false,
  //     views: 3781401,
  //   } , 
  //   {
  //     channelID: "UCgqGpYjhnWvhE5-QrmXLkoQ",
  //     channelImg: "https://yt3.ggpht.com/ytc/AKedOLQ_DlBgMDMT4ARdLuB1dZXTFAoJ4aLNNgn1IBAf=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "The StudyTube Project",
  //     description: null,
  //     duration: "15:34",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/I-k-iTUMQAY/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBMWlD0HW9FwyDutkppZ3Ywz7jbmQ",
  //     title: "basics of CODING in 10 minutes",
  //     uploadedAt: "1 year ago",
  //     url: "https://www.youtube.com/watch?v=I-k-iTUMQAY",
  //     verified: false,
  //     views: 521716,
  //   } ,
  //   {
  //     channelID: "UCRLEADhMcb8WUdnQ5_Alk7g",
  //     channelImg: "https://yt3.ggpht.com/2Ic5G-MGcf0BGlxLo86TkUZILkxKCenzjCszCyVJSRcmn5xkEgtLgs4CBCkaK2YNoNdX4A66=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "Aaron Jack",
  //     description: null,
  //     duration: "5:59",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/CIRGjwYgdT4/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC8zR0ndjTZ3QCVuJMqp6Kb-G56UQ",
  //     title: "Programming vs Coding - What's the difference?",
  //     uploadedAt: "9 months ago",
  //     url: "https://www.youtube.com/watch?v=CIRGjwYgdT4",
  //     verified: true,
  //     views: 745652,
  //   } , 
  //   {
  //     channelID: "UCT5RMcRGa32Th0AZ0Dxxviw",
  //     channelImg: "https://yt3.ggpht.com/ytc/AKedOLRLLwKZPAC0lqMM8kQ-2a0Z6a5SC3Q3OB4sod2z=s68-c-k-c0x00ffffff-no-rj",
  //     channelTitle: "JimTV",
  //     description: null,
  //     duration: "1:00:03",
  //     subs: 118207,
  //     thumbnails: "https://i.ytimg.com/vi/l9nh1l8ZIJQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCjUXoFFhtydmIQO915lf-U4aebNA",
  //     title: "Programming / Coding / Hacking music vol.16 (CONN...",
  //     uploadedAt: "2 years ago",
  //     url: "https://www.youtube.com/watch?v=l9nh1l8ZIJQ",
  //     verified: false,
  //     views: 3781401,
  //   }
  // ] 

  
